### ISSUE TITLE
[Spike] Investigate possible JCypher integrations

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquigraph#138]

**Comment by jpopadak** [comment]
Another possibility could be a QueryDSL integration: https://github.com/neo4j-contrib/cypher-dsl

**Comment by fbiville** [comment]
Wow, super interesting! Would you be interested in prototyping something? :)

**Comment by jpopadak** [comment]
Possibly.The good thing about QueryDSL / `cypher-dsl` is that Neo4j backs it, unlike JCypher.

**Comment by fbiville** [comment]
An alternative to using a DSL would be to parse Cypher strings, as suggested by https://github.com/liquigraph/liquigraph/issues/175.
