### ISSUE TITLE
Use lightweight markup language for documentation

### ISSUE THREAD

**Issue by mvitz** [liquibase/liquigraph#159]
GitHub is capable of rendering markdown for GitHub pages. I think writing the documentation in markdown would be a lot easier than using the raw HTML.

**Comment by fbiville** [comment]
I would even go with Asciidoctor :-)
I've already done a few things with it, such as https://fbiville.github.io/neo4j-training/ and https://github.com/fbiville/annotation-processing-ftw.

**Comment by fbiville** [comment]
Currently working on https://github.com/fbiville/liquigraph-docs FYI. Almost complete.

**Comment by fbiville** [comment]
and it's live now!
