### ISSUE TITLE
[Core] Support CSV import

### ISSUE THREAD

**Issue by fbiville** [liquibase/liquigraph#193]
And implement a shim for older 2.x versions of Neo4j that do not support it.
That way, we could also use Liquigraph to import initial dumps :)

**Comment by sey** [comment]
I think I get you want to load complete db dumps from CSV.
I'm already using `LOAD CSV`... command in LiquiGraph and it works. 
One limitation currently is that queries in a changeset are executed in a transaction which prevents the use of `USING PERIODIC COMMIT`.
It would be a nice addition while working on importing from CSV data to be able to mark a changeset as transaction-free (with an attribute).
