### ISSUE TITLE
[3.x] Document support of bolt+routing

### ISSUE THREAD

**Issue by ericsantosn** [liquibase/liquigraph#210]
I'm trying to use this liquidgraph tool to manage our schemas on neo4j and endup in a situation where to url below works

> jdbc:neo4j:bolt://neo4j:7687

but this one

> jdbc:neo4j:bolt+routing://neo4j:7687

I get

> ERROR com.hubrick.recommendation.Neo4JMigrationExecutor - Migration failed error=java.sql.SQLException: JDBC URL is not correct.

Apparently from what I can see the neo4j driver that liquidgraph is using does not support routing yet?

routing for us is really important since we have cluster and without rounting it might happen that the migration will run in the FOLLOWER and not in the LEADER and then fail right away since it does not have writing access.

So is the any option to make it work?

https://stackoverflow.com/questions/50740273/liquidgraph-does-not-support-boltrouting-in-the-url

**Comment by fbiville** [comment]
@ericsantosn hi, thanks for the report!
Have you explicitly upgraded the Bolt JDBC driver to a version that supports it?
Would you mind sharing your classpath (via `mvn dependency:tree` or equivalent)?

**Comment by ericsantosn** [comment]
Hi @fbiville so I check with neo4j guys what happens is that the driver does not support bolt+routing, but apparently they are working in a new version of this driver to support routing.

**Comment by fbiville** [comment]
Oh I see, I thought it was released already, I remember a Pull Request on neo4j-contrib/neo4j-jdbc was merged a few weeks ago to support that.

**Comment by fbiville** [comment]
https://github.com/neo4j-contrib/neo4j-jdbc/pull/130

**Comment by fbiville** [comment]
If you do not want to wait for 3.3.1 to be released, you build https://github.com/neo4j-contrib/neo4j-jdbc yourself and use that as a dependency.

**Comment by ericsantosn** [comment]
@fbiville i will try that, cause right now even if I replace with 3.3.0 i still get the issue, thx for your time!

**Comment by fbiville** [comment]
3.3.1 is out: https://github.com/neo4j-contrib/neo4j-jdbc/releases/tag/3.3.1

**Comment by ericsantosn** [comment]
@fbiville trying it right now!

**Comment by fbiville** [comment]
@ericsantosn how did it go? Any issue?

**Comment by ericsantosn** [comment]
@fbiville sorry I forgot to get back to you! it worked, and works like a charm. thanks!

**Comment by fbiville** [comment]
Did you find enough documentation to achieve what you wanted to do? Should it be augmented?

**Comment by fbiville** [comment]
Yep, I just wondered if it would be valuable to add this in the documentation.

**Comment by ericsantosn** [comment]
I guess that might be valuable, at least till a new release of liquidgraph.

**Comment by robertlagrant** [comment]
@fbiville is the newer version likely to be in liquigraph at some point? I see it's still pinned to 3.1.0 in the pom.xml.

**Comment by fbiville** [comment]
@robertlagrant if it works, it should be documented
However, Liquigraph on `master` has to remain compatible with all Neo4j 3.x versions and as far as I remember, the recent releases of the JDBC driver introduces backwards incompatibilities. 
Happy to merge documentation PRs!
