### ISSUE TITLE
How can I define and execute rollbacks?

### ISSUE THREAD

**Issue by sintezcs** [liquibase/liquigraph#240]
In liquibase, you can [define "rollback" queries](https://www.liquibase.org/documentation/rollback.html) in your migration XML files, and then rollback your changeset by executing a command. Is it possible to do something similar with Liquigraph? How can I define and execute rollback queries?

**Comment by fbiville** [comment]
Hi, and thanks for the report!
It's currently not possible but it would be a welcome addition.
Would you be interested in contributing this feature? If so, I can guide you through the codebase.

**Comment by fbiville** [comment]
I'll pitch the feature in the next Paris Hackergarten meetup (in 1 week!). :)

**Comment by sintezcs** [comment]
That would be great!

**Comment by sintezcs** [comment]
hey, any updates on this?

**Comment by fbiville** [comment]
Hello. I have been working on a Neo4j plugin for Liqui**base**: https://github.com/liquibase/liquibase-neo4j.
It will be released soon and supports rollbacks among other things.

There won't be any migration helper from Liquigraph in that first release, but that will be included in the next one.

**Comment by fbiville** [comment]
This is supported by the successor of Liquigraph: https://github.com/liquibase/liquibase-neo4j.
A migration path from Liquigraph to Liquibase is on its way.
