### ISSUE TITLE
.cypher file changelogs

### ISSUE THREAD

**Issue by xenoterracide** [liquibase/liquigraph#396]
So I'm pretty familiar with liquibase, less so with this (literally I only skimmed the getting started)  project and neo4j. what I'm basically asking for is this feature of liquibase https://docs.liquibase.com/concepts/basic/sql-format.html but obviously for cypher.

**Comment by fbiville** [comment]
Hi, thanks for reporting this.

The only format is currently XML, with the `<query>` tag. This tag is roughly equivalent to Liquibase's [SQL tag](https://docs.liquibase.com/change-types/community/sql.html).

Is there a particular constraint here to avoid XML files?

**Comment by xenoterracide** [comment]
verbose, and syntax highlighting doesn't tend to work well in them, also *if* there was a plugin introspecting the database, auto completion of nodes wouldn't work.

**Comment by fbiville** [comment]
Auto-completion could work for either format, I think. 

I sympathize with the issues you raise:
- it's indeed more verbose (for simple migration queries*)
- XML may not be the most popular format

*readability may suffer with pre- and post-conditions

However, there are advantages:
- you get to define a schema and validate against it (although it does not validate Cypher queries - this could be done at runtime via https://github.com/liquigraph/liquigraph/issues/175)
- parsing basically comes for free

Honestly, this is not high in my TODO list but I'm happy to offer guidance to anyone willing to introduce this format.

**Comment by xenoterracide** [comment]
> Auto-completion could work for either format, I think.

yeah but a lot of syntax parser's highlighters don't deal with nested languages, and even if they do they often do it poorly.

**Comment by fbiville** [comment]
@xenoterracide hi, multi-format (including Cypher, aka "SQL") is supported by the successor of Liquigraph: https://github.com/liquibase/liquibase-neo4j.
A migration path from Liquigraph to Liquibase is on its way.
